import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Weather from '../components/weather'
import Status from '../components/status'
import Link from 'next/link'
import {GraphQLClient, gql} from 'graphql-request'

const graphcms = new GraphQLClient(`https://api-ap-south-1.graphcms.com/v2/cl4doen4r64qw01xu8aht6kqs/master`)

let myDate = new Date()
var today = myDate.toISOString().split('T')[0]

const QUERY = gql`
{
  dailyRecords(where: {date: "${today}"}) {
    date
    n
    p
    k
    humidity
    ph
    rainfall
  }
}`

export async function getStaticProps() {
  const posts = await graphcms.request(QUERY);
  return {
    props: {
      posts
    },
    revalidate: 30
  };
}

export default function Home( {posts} ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>SvayaKT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href={`/`}><span className={styles.brandname}>SvayaKT!</span></Link>
        </h1>

        <p className={styles.description}>
          Your e-Agricultural Ecosystem{' '}
        </p>

        <div className={styles.grid}>
          <div className={styles.warningcard}>
            <h2>⚠️Warning &rarr;</h2>
            <p>Soil moisture under recommended levels</p>
          </div>

          <Weather/>

          {console.log(posts)}

          <div className={styles.card}>
            <h2>Status &rarr;</h2>
            <p>N: {posts.dailyRecords[0].n}</p>
            <p>P: {posts.dailyRecords[0].p}</p>
            <p>K: {posts.dailyRecords[0].k}</p>
            <p>Humidity: {posts.dailyRecords[0].humidity}</p>
            <p>pH: {posts.dailyRecords[0].ph}</p>
            <p>Rainfall: {posts.dailyRecords[0].rainfall}</p>
          </div>

          {/* {posts.dailyRecords.map((data) => {
            <div className={styles.card}>
              <h2>Date: {data.date} &rarr;</h2>
              <p>N: {data.n}</p>
              <p>P: {data.p}</p>
              <p>K: {data.k}</p>
              <p>Humidity: {data.humidity}</p>
              <p>pH: {data.ph}</p>
              <p>Rainfall: {data.rainfall}</p>
            </div>
          })} */}

          {/* <Status/> */}










          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}
          {/* */}

          <Link href={`/markets/tomato`}>
            <div className={styles.card}>
              <h2>🍅Tomato market &rarr;</h2>
              <p><b>Today:</b> ₹21</p>
              <p><b>Tomorrow:</b> ₹23.5</p>
              <p><b>Next week:</b> ₹24.7</p>
            </div>
          </Link>

          <Link href={`/markets/potato`}>
            <div className={styles.card}>
              <h2>🥔Potato market &rarr;</h2>
              <p><b>Today:</b> ₹27</p>
              <p><b>Tomorrow:</b> ₹28.1</p>
              <p><b>Next week:</b> ₹30.2</p>
            </div>
          </Link>

          <Link href={`/markets/brinjal`}>
            <div className={styles.card}>
              <h2>🍆Brinjal market &rarr;</h2>
              <p><b>Today:</b> ₹24.23</p>
              <p><b>Tomorrow:</b> ₹23.46</p>
              <p><b>Next week:</b> ₹21.78</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
          <span className={styles.brandname}>
            <b>SvayaKT</b>
          </span>
          &nbsp; by 1BY18IS 004/024/057
      </footer>
    </div>
  )
}
